columns_to_keep:
  - country
  - iso_code
  - year
  - population
  - gdp
  - biofuel_electricity
  - biofuel_share_elec
  - carbon_intensity_elec
  - coal_electricity
  - coal_share_elec
  - electricity_demand
  - electricity_generation
  - electricity_share_energy
  - fossil_elec_per_capita
  - fossil_electricity
  - fossil_share_elec
  - gas_electricity
  - gas_share_elec
  - hydro_electricity
  - hydro_share_elec
  - low_carbon_elec_per_capita
  - low_carbon_electricity
  - low_carbon_share_elec
  - nuclear_electricity
  - nuclear_share_elec
  - oil_electricity
  - oil_share_elec
  - other_renewable_electricity
  - other_renewable_exc_biofuel_electricity
  - other_renewables_elec_per_capita
  - other_renewables_elec_per_capita_exc_biofuel
  - other_renewables_share_elec
  - other_renewables_share_elec_exc_biofuel
  - per_capita_electricity
  - renewables_elec_per_capita
  - renewables_electricity
  - renewables_share_elec
  - solar_electricity
  - solar_share_elec
  - wind_electricity
  - wind_share_elec

active_year: 2022
previous_year_range: 5
