# .github/workflows/process_energy_data.yml

name: Process Energy Data and Update Codebook

on:
  workflow_dispatch:  
  schedule:
    - cron: '0 0 * * 0'  

jobs:
  process-energy-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'  # Update this to a compatible version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run energy data processing script
      run: |
        python scripts/energy_data_processing.py

    - name: Run codebook update script
      run: |
        python scripts/update_codebook.py

    - name: List contents of output directory
      run: |
        ls -la output/

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add -f output/*.csv
        git commit -m "Update processed energy data and codebook" || echo "Nothing to commit"
        git push

    - name: Clean up unnecessary files
      run: |
        rm -rf owid-energy-data.csv
        rm -rf owid-energy-codebook.csv
