# GitHub Actions Workflow to Run Energy Data Processing and Codebook Update

name: Process Energy Data and Update Codebook

on:
  workflow_dispatch:  # Allows manual trigger of the workflow
  schedule:
    - cron: '0 0 * * 0'  # Schedule to run weekly on Sundays at midnight

jobs:
  process-energy-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: 3.8

    - name: Cache Python packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests pyyaml
        xargs -a os-packages.txt sudo apt-get install -y

    - name: Run energy data processing script
      run: |
        python scripts/energy_data_processing.py

    - name: Run codebook update script
      run: |
        python scripts/update_codebook.py

    - name: Clean up unnecessary files
      run: |
        rm -rf owid-energy-data.csv
        rm -rf owid-energy-codebook.csv

    - name: Commit and push changes
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add output/processed_energy_data.csv output/codebook.csv

        # Check if there are any staged changes and decide action accordingly
        if git diff --cached --quiet; then
          echo "No changes detected, nothing to commit."
        else
          echo "Changes detected, committing and pushing..."
          git commit -m "Update processed energy data and codebook"
          # Use a more secure way to push without exposing the token
          git push "https://${GH_TOKEN}@github.com/syncneural/data.git" HEAD:main
          echo "Changes have been successfully pushed."
        fi

    - name: Post job cleanup
      if: always()
      run: |
        echo "Running post-job cleanup to minimize workspace size..."
        # Optionally clean up other temporary files here if necessary
