name: Process Energy Data

on:
  push:
    branches:
      - main

jobs:
  process-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: 3.8

    - name: Cache Python packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests pyyaml

    - name: Create output directory
      run: mkdir -p output

    - name: Run energy data processing script
      run: python scripts/energy_data_processing.py

    - name: Run codebook update script
      run: python scripts/update_codebook.py

    - name: Verify output files existence
      run: |
        if [ -f "output/processed_energy_data.csv" ]; then
          echo "Processed energy data CSV exists."
        else
          echo "Processed energy data CSV does not exist." && exit 1
        fi
        if [ -f "output/codebook.csv" ]; then
          echo "Codebook CSV exists."
        else
          echo "Codebook CSV does not exist." && exit 1
        fi

    - name: Force add output files
      run: |
        git add -f output/processed_energy_data.csv output/codebook.csv
        git update-index --refresh

    - name: Touch files to ensure modification
      run: |
        touch output/processed_energy_data.csv
        touch output/codebook.csv

    - name: Debug Git Status
      run: git status

    - name: Debug Git Diff
      run: git diff

    - name: Commit and push changes
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git commit -m "Update processed energy data and codebook" || echo "Nothing to commit"
        git push "https://${GH_TOKEN}@github.com/syncneural/data.git" HEAD:main || echo "No changes to push"
