# GitHub Actions Workflow to Run Energy Data Processing and Codebook Update

name: Process Energy Data and Update Codebook

on:
  workflow_dispatch:  # Allows manual trigger of the workflow
  schedule:
    - cron: '0 0 * * 0'  # Schedule to run weekly on Sundays at midnight

jobs:
  process-energy-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Cache Python packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests pyyaml

    - name: Cache OS packages
      id: os-cache
      uses: actions/cache@v3
      with:
        path: /usr/local/lib
        key: ${{ runner.os }}-os-packages-${{ hashFiles('os-packages.txt') }}
        restore-keys: |
          ${{ runner.os }}-os-packages-

    - name: Install OS dependencies
      if: steps.os-cache.outputs.cache-hit != 'true'
      run: |
        sudo apt-get update
        xargs -a os-packages.txt sudo apt-get install -y

    - name: Run energy data processing script
      run: |
        python scripts/energy_data_processing.py

    - name: Run codebook update script
      run: |
        python scripts/update_codebook.py

    - name: Commit and push changes
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add output/processed_energy_data.csv
        git add output/codebook.csv

        # Check if there are any changes
        if git diff-index --quiet HEAD; then
          echo "No changes detected, nothing to commit."
          exit 0  # Exit gracefully with a success code
        fi

        echo "Changes detected, committing and pushing..."
        git commit -m "Update processed energy data and codebook" || {
          echo "Commit failed: No changes to commit."
          exit 0  # Exit gracefully, as this is not an error case
        }

        git push https://x-access-token:${GH_TOKEN}@github.com/syncneural/data.git HEAD:main || {
          echo "Push failed. Please check repository permissions and access tokens."
          exit 1  # Exit with failure if push fails
        }
        echo "Changes have been successfully pushed."
