# GitHub Actions Workflow to Run Energy Data Processing

name: Process Energy Data

on:
  workflow_dispatch:  # Allows manual trigger of the workflow
  schedule:
    - cron: '0 0 * * 0'  # Schedule to run weekly on Sundays at midnight

jobs:
  process-energy-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Updated to use version 3 which supports Node.js 16/20

    - name: Set up Python 3.8
      uses: actions/setup-python@v4  # Updated to use version 4 which supports Node.js 16/20
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests

    - name: Run energy data processing script
      run: |
        python scripts/energy_data_processing.py  # Adjust path if script is saved in a different directory

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add output/processed_energy_data.csv
        git commit -m "Update processed energy data"
        git push
